name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false

    name: Windows Development
    runs-on: [Windows, X64, self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build & Cook
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: ${{ github.workspace }}/HotGirlBaseBall.uproject
        BUILD_CONFIG: Development
        PLATFORM: Win64
        CLEAN: false
        COOK: true
        STAGE: false
        PACKAGE: false
        PAK: false
        SERVER: false
        ARCHIVE: false
        EDITOR: true
        ENCRYPT_INI: false

