name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:

  build_pc:
    strategy:
      fail-fast: false

    name: Windows and Linux
    runs-on: [Windows, X64, self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build & Cook Windows Development
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: ${{ github.workspace }}/HotGirlBaseBall.uproject
        BUILD_CONFIG: Development
        PLATFORM: Win64
        CLEAN: false
        COOK: true
        STAGE: false
        PACKAGE: false
        PAK: false
        SERVER: false
        ARCHIVE: false
        EDITOR: true
        ENCRYPT_INI: false

    - name: Build & Cook Linux Development
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: ${{ github.workspace }}/HotGirlBaseBall.uproject
        BUILD_CONFIG: Development
        PLATFORM: Linux
        CLEAN: false
        COOK: true
        STAGE: false
        PACKAGE: false
        PAK: false
        SERVER: false
        ARCHIVE: false
        EDITOR: false
        ENCRYPT_INI: false

    - name: Package Windows Development
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: ${{ github.workspace }}/HotGirlBaseBall.uproject
        BUILD_CONFIG: Development
        PLATFORM: Win64
        CLEAN: false
        COOK: true
        STAGE: true
        PACKAGE: true
        PAK: true
        SERVER: false
        ARCHIVE: true
        ARCHIVE_PATH: 'C:/HGBB/Win64Development'
        EDITOR: false
        ENCRYPT_INI: false

    - name: Package Windows Shipping
      uses: OrchidIsle/UE5-Build-Project@latest
      with:
        RUNUAT_PATH: 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat'
        UPROJECT_PATH: ${{ github.workspace }}/HotGirlBaseBall.uproject
        BUILD_CONFIG: Shipping
        PLATFORM: Win64
        CLEAN: false
        COOK: true
        STAGE: true
        PACKAGE: true
        PAK: true
        SERVER: false
        ARCHIVE: true
        ARCHIVE_PATH: 'C:/HGBB/Win64Shipping'
        EDITOR: false
        ENCRYPT_INI: false

    - name: Deploy Development to Steam dev branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/WinDev.vdf +quit
    
    - name: Deploy Shipping to Steam pre branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/WinPre.vdf +quit

  build_apple:
    name: Apple
    runs-on: [macOS, ARM64, self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build & Cook macOS Development
      shell: bash
      run: '/Users/Shared/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseBall.uproject' -clientconfig=Development -serverconfig=Development -platform=Mac -cook
