name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:

  build_windows:
    name: Windows
    runs-on: [Windows, X64, self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build & Cook Windows Development
      run: "cmd /c 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Win64 -build -cook -noP4 -unattended -utf8output -prereqs"

    - name: Package Windows Development
      run: "cmd /c 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Win64 -build -cook -stage -package -pak -archive -archivedirectory='C:/HGBB/Win64Development' -noP4 -unattended -utf8output -prereqs"

    - name: Package Windows Shipping
      run: "cmd /c 'C:/Program Files/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.bat' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Shipping -serverconfig=Shipping -platform=Win64 -CrashReporter -build -cook -stage -package -pak -archive -archivedirectory='C:/HGBB/Win64Shipping' -noP4 -unattended -utf8output -prereqs"

    - name: Write BugSplat Config To Windows Build
      run: ${{ github.workspace }}/Scripts/ConfigureBugSplat.bat C:\HGBB\Win64Shipping

    - name: Upload Windows Debug Symbols to BugSplat
      working-directory: C:\HGBB\Win64Shipping
      run: ${{ github.workspace }}/Plugins/BugSplat/Source/ThirdParty/SymUploader/symbol-upload-windows.exe -i ${{ secrets.BUGSPLAT_CLIENTID }} -s ${{ secrets.BUGSPLAT_CLIENTSECRET }} -b hotgirlbaseball -a HotGirlBaseball -v 0.1.0 -f "**/*.{pdb,exe,dll}"

    - name: Deploy Windows Development to Steam dev branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/WinDev.vdf +quit

    - name: Deploy Windows Shipping to Steam pre branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/WinPre.vdf +quit

  build_linux:
    name: Linux
    runs-on: [Linux, X64, self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Build & Cook Linux Development
      run: "sh '/opt/ue5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Linux -build -cook -noP4 -unattended -utf8output -prereqs"

    - name: Package Linux Development
      run: "sh '/opt/ue5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Linux -CrashReporter -build -cook -stage -package -pak -archive -archivedirectory='/opt/hgbb/LinuxDevelopment' -noP4 -unattended -utf8output -prereqs"

    - name: Package Linux Shipping
      run: "sh '/opt/ue5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Shipping -serverconfig=Shipping -platform=Linux -CrashReporter -build -cook -stage -package -pak -archive -archivedirectory='/opt/hgbb/LinuxShipping' -noP4 -unattended -utf8output -prereqs"

    - name: Write BugSplat Config To Linux Build
      run: "sh '${{ github.workspace }}/Scripts/ConfigureBugSplat.sh' /opt/hgbb/LinuxShipping"

    - name: Upload Linux Debug Library Symbols to BugSplat
      working-directory: /opt/hgbb/LinuxShipping/
      run: ${{ github.workspace }}/Plugins/BugSplat/Source/ThirdParty/SymUploader/symbol-upload-linux -i ${{ secrets.BUGSPLAT_CLIENTID }} -s ${{ secrets.BUGSPLAT_CLIENTSECRET }} -b hotgirlbaseball -a HotGirlBaseball -v 0.1.0 -f "**/*.{so,0,debug,sym}"

    - name: Upload Linux Debug Executable Symbols to BugSplat
      working-directory: /opt/hgbb/LinuxShipping
      run: ${{ github.workspace }}/Plugins/BugSplat/Source/ThirdParty/SymUploader/symbol-upload-linux -i ${{ secrets.BUGSPLAT_CLIENTID }} -s ${{ secrets.BUGSPLAT_CLIENTSECRET }} -b hotgirlbaseball -a HotGirlBaseball -v 0.1.0 -f "**/HotGirlBaseball*"

    - name: Deploy Linux Development to Steam dev branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/LinDev.vdf +quit

    - name: Deploy Linux Shipping to Steam pre branch
      run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/LinPre.vdf +quit

  # Disabling apple build due to cook crash with mutable ; to be diagnosed
  #build_apple:
  #  name: Apple
  #  runs-on: [macOS, ARM64, self-hosted]
  #  steps:
  #  - uses: actions/checkout@v4
  #    with:
  #      lfs: true
  #  - name: Build & Cook macOS Development
  #    run: "'/Users/Shared/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Mac -build -cook -noP4 -unattended -utf8output -prereqs -specifiedarchitecture=arm64+x86_64"
  #  - name: Package macOS Development
  #    run: "'/Users/Shared/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Development -serverconfig=Development -platform=Mac  -build -cook -package -pak -archive -archivedirectory='/Users/Shared/HGBB/MacDevelopment' -noP4 -unattended -utf8output -prereqs -specifiedarchitecture=arm64+x86_64"
  #  - name: Package macOS Shipping
  #    run: "'/Users/Shared/Epic Games/UE_5.5/Engine/Build/BatchFiles/RunUAT.sh' BuildCookRun -project='${{ github.workspace }}/HotGirlBaseball.uproject' -clientconfig=Shipping -serverconfig=Shipping -platform=Mac  -build -cook -package -pak -archive -archivedirectory='/Users/Shared/HGBB/MacShipping' -noP4 -unattended -utf8output -prereqs -specifiedarchitecture=arm64+x86_64"
  #  - name: Deploy macOS Development
  #    run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/MacDev.vdf +quit
  #  - name: Deploy macOS Shipping
  #    run: steamcmd +login ${{ secrets.STEAM_USERNAME }} +run_app_build ${{ github.workspace }}/Steam/MacPre.vdf +quit